name: Health Check

on:
  schedule:
    - cron: '0 10 1 * *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed website URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://bloglist-app-fyb1.onrender.com/health
      - name: Notify Discord on Success
        if: success()
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'GitHub ${{ github.actor }} Bot - Health Check'
          avatar-url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
          content: 'Health check passed for BlogApp'
          embed-title: 'BlogApp Health Check'
          embed-color: 3077745
          embed-description: 'URL: https://bloglist-app-fyb1.onrender.com/health'
      - name: Notify Discord on failure
        if: failure()
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'GitHub ${{ github.actor }} Bot - Health Check'
          avatar-url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
          content: 'Health check failed for BlogApp'
          embed-title: 'BlogApp Health Check'
          embed-color: 16731196
          embed-description: 'URL: https://bloglist-app-fyb1.onrender.com/health'
