name: CI/CD-pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ vars.PORT }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Instalar variables de entorno
        run: |
          echo "PORT=${PORT}" >> .env
          echo "TEST_MONGODB_URI=${TEST_MONGODB_URI}" >> .env
          echo "SECRET=${SECRET}" >> .env
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: npm run test:e2e
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')  }}
        run: curl -X POST https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
